/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2024-11-19 07:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import community.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("community");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

int idx = 0;
if(request.getParameter("idx") != null){
	idx = Integer.parseInt(request.getParameter("idx"));
	//parseint : 문자열을 파싱[구문분석]하여 특정진수의 정수로 리턴
	//문장이 이루고 있는 구성성분을 분해하고 성분의 위계 관계를 분석하여 결정
}

//만약 넘어온 데이터가 없다면
if(idx == 0){
	PrintWriter script = response.getWriter();
	script.println("<script>");
	script.println("alert('개발자여 오타 났음')");
	script.println("window.location.href='index.jsp'");
	script.println("</script>");
}

//오타가 (99번 까지 오타 100번재 네트워크 오류)나지 않앗다면 구체적인 실존하는 글에 정보를 담는다
Board board = new BoardDAO().getBoard(idx);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 조회</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("커뮤니티 사이트\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content_body\">\r\n");
      out.write("<!--  <p>총 10개의 게시물이 있습니다</p>-->\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"\">\r\n");
      out.write("<h1 style=\"text-align:center;\">게시물 조회</h1>\r\n");
      out.write("<p>제목 : \r\n");
      out.print( board.getSubject() );
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("<p>작성자 : ");
      out.print( board.getWriter() );
      out.write(" <span>작성일 : ");
      out.print( board.getDate() );
      out.write("</span></p>\r\n");
      out.write("<p>\r\n");
      out.write("내용 :");
      out.print( board.getContent() );
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("<div class=\"btn-wrap\">\r\n");
      out.write("<a href=\"index.jsp\">목록</a>\r\n");
      out.write("<a href=\"edit.jsp?idx=");
      out.print(idx);
      out.write("\">수정</a>\r\n");
      out.write("<a href=\"deleteAction.jsp?idx=");
      out.print(idx);
      out.write("\" onclick=\"return confirm('정말로 삭제하시겠습니까?')\">\r\n");
      out.write("삭제\r\n");
      out.write("</a>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("Copyright (C) 2018 정보처리산업기사 ALL Right Reserved\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
